# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

numVM = 3
Vagrant.configure("2") do |config|
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.ssh.insert_key = false
  config.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
  config.vm.provision "shell", inline: <<-EOC
    sudo sed -i -e "\\#PasswordAuthentication yes# s#PasswordAuthentication yes#PasswordAuthentication no#g" /etc/ssh/sshd_config
    sudo systemctl restart sshd.service
    echo "finished"
  EOC

  (1..numVM).each do |i|
    config.vm.hostname = "rl#{i}"
    config.vm.define "rl_routing#{i}" do |node|
      node.vm.box = "justus/rl_routing"
      node.vm.hostname = "rl#{i}"
      node.vm.provision "shell",
      inline:  "echo '127.0.0.1 rl#{i}' >> /etc/hosts
                   echo 'rl#{i}' > /etc/hostname
                   hostname `cat /etc/hostname`"

      node.vm.provider :libvirt do |libvirt|
        libvirt.management_network_autostart = true
        libvirt.driver = "kvm"
        libvirt.cpus = 2
        libvirt.cpu_mode = "host-passthrough"
        libvirt.memory = 4096
      end
    end
  end
end
